# Generated by Django 4.1.2 on 2022-11-28 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Journal',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, default=datetime.datetime.today)),
                ('meal_type', models.CharField(max_length=30)),
                ('Food', models.ManyToManyField(blank=True, to='dashboard.food')),
            ],
            options={
                'db_table': 'Journal Entry',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrientName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Nutrient',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('stage', models.CharField(blank=True, max_length=30)),
                ('comorbidity_type', models.CharField(blank=True, max_length=30)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.journalentry')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.nutrient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
            options={
                'db_table': 'Recommendation',
                'unique_together': {('user', 'nutrient')},
            },
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.nutrient')),
            ],
            options={
                'db_table': 'Food Nutrient',
                'unique_together': {('nutrient', 'food')},
            },
        ),
        migrations.CreateModel(
            name='ConsumedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.journalentry')),
            ],
            options={
                'db_table': 'Consumed Food',
                'unique_together': {('food', 'journal_entry')},
            },
        ),
    ]
