# Generated by Django 4.1.2 on 2022-11-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Metrics',
        ),
    ]
