# Generated by Django 4.1.2 on 2022-11-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrient',
            old_name='quantity',
            new_name='actual_amount',
        ),
    ]
