# Generated by Django 4.1.2 on 2022-11-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_quantity_foodnutrient_actual_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='food',
            name='nutrient',
            field=models.ManyToManyField(blank=True, to='dashboard.nutrient'),
        ),
    ]
