# Generated by Django 4.1.2 on 2022-11-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_journalentry_meal_type_food_nutrient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='user',
            name='height_inches',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
