# Generated by Django 4.1.3 on 2022-11-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_user_height_remove_user_journal_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrient',
            old_name='nutrientName',
            new_name='nutrient_name',
        ),
    ]
