# Generated by Django 4.1.2 on 2022-11-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_journalentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
    ]
